### ISSUE TITLE
Ores Found In BM Mark of the Falling Tower Meteors

### ISSUE THREAD

**Issue by Sentrus** [breakinblocks/everything-is-hostile#15]
Nether Star
-----------
Nether Quartz
Certus Quartz
Diamond
Moonstone
Sunstone
Emerald

Diamond
-------
Cinnabar
Amber
Diamond
Emerald

Iron Block
----------
Abyssal Copper
Abyssal Tin
Redstone
Silver (ProjRed)
Iron
Lapis
Gold

Stone
----------
Coal
Iron
Apatite

**Comment by Milkyway3640** [comment]
We should add Chimerite and Vinteum dust. Also maybe the TC shards.

**Comment by Sentrus** [comment]
Yeah Saereth has a list I think. He just wanted me to confirm what's already spawning. Which is... frankly not much. I wonder why some AM2 stuff showed up, and others didn't. And Cobalt/Ardite nowhere to be seen. I don't remember having to add those manually before, but maybe I'm remember incorrectly.

**Comment by Milkyway3640** [comment]
Blood magic has a config to set certain ores to spawn in each meteor, there's a few things by default, but the AM2 stuff was probably added, but not totally finished.

**Comment by Saereth** [comment]
meteors expanded a bit and lots of new ores added!
