### ISSUE TITLE
Ores Found in Botania Orechid Testing

### ISSUE THREAD

**Issue by Sentrus** [breakinblocks/everything-is-hostile#16]
Orechid
-------
Vinteum
Abyssal Copper
Abyssal Tin
Coal
Redstone
Certus Quartz
Aluminum
Chimerite
Iron
Blue Topaz
Amber
Silver
Ruby
Cinnabar
Emerald
Air Infused Stone
Gold
Dark Ore
Apatite
Diamond
Lapis
Sapphire
Order Infused Stone
Fire Infused Stone

Obviously this is an incomplete list as some of the rarer stuff probably just didn't show up during my testing.

**Comment by Saereth** [comment]
nice, looks like we'll only have to add a couple into the orechid
