### ISSUE TITLE
Redundant Bedrockium Material for TiCon & Stat Oddities

### ISSUE THREAD

**Issue by Sentrus** [breakinblocks/everything-is-hostile#21]
Parts made in casting table have meta :185
Redundant parts have meta :315

Also Bedrockium parts, despite having awesome durability listed, don't seem to give durability when used for Ranged Weapons. They are worse than literally every other material. Bedrockium durability does seem to work fine for tools.

**Comment by Saereth** [comment]
removed 315 recipes, its different itemids for each one though so nei pruning will have to come later. Also bedrockium isnt registered for use in ranged weapons as anything other than stone, so basically its just crap for bows and whatnot, tic doesnt have a setting to modify that directly so I'll have to see what, if anything I can do about that in the future, for now this is mostly resolved.
