### ISSUE TITLE
Pendant recipes not proper 

### ISSUE THREAD

**Issue by Debu922** [breakinblocks/everything-is-hostile#26]
Chromaticraft Pendant recipes aren't visible, and hence "uncraftable".
![2015-07-12_00 33 39](https://cloud.githubusercontent.com/assets/13169482/8635003/6b10d8dc-282e-11e5-82f1-df2d06a4d247.png)

**Comment by Saereth** [comment]
This is not a bug, hit the left/right arrows, you'll see it needs and advanced casting multistructure and runes/pylon energy to create
