### ISSUE TITLE
Bug - World gen

### ISSUE THREAD

**Issue by Debu922** [breakinblocks/everything-is-hostile#3]
Due to some world gen, plants are being uprooted, and they fall as their drops, this might cause lag upon server start.

**Comment by Milkyway3640** [comment]
This is due to the worldgen from the dungeons in chocolate craft and the like,  correct?

This might be a valid concern,  but, within 5 minutes or if an admin/mod clears items manually,  they'll be gone. 

I mean, having random items on the ground isn't good, but,  it's an easily rectified problem.

**Comment by Saereth** [comment]
Yeah this is a pain for vazkii or the nod authors to remedy so it probably
won't, but it's not a huge issue
