### ISSUE TITLE
Bee Prepared!

### ISSUE THREAD

**Issue by Gammelkebab** [breakinblocks/everything-is-hostile#35]
The HQM quest "Bee Prepared!" doesn't recognize the bees. It should look for the exact bees you get when breaking the natural hives. Including NBT and META.

**Comment by Saereth** [comment]
Fixed in the next update

**Comment by MrScopi** [comment]
I am not sure this got fixed yet, because I completed the quest without even having seen enough princesses, much less specific ones.
