### ISSUE TITLE
CompactStorage Alternative

### ISSUE THREAD

**Issue by Gammelkebab** [breakinblocks/everything-is-hostile#42]
We've noticed that piping items into a CompactStorage chest (tried pumping from another of them) didnt stop when the chest was full. We used enderIO item Conduits. The items kept getting pumped from the input chest and since the output chest was full they just vanished.
Now i guess we can't actually fix that but we could replace CompactStorage with something not eating items.

**Comment by Milkyway3640** [comment]
I don't see why saereth couldn't add another storage solution,  however,  removing compact storage would be way worse.  Anything that's in a compact storage chest, crate, or backpack would vanish into thin air.  Removing compact storage isn't really an option, but adding something else is feasible.

**Comment by Saereth** [comment]
Reported to the mod author, just dont pipe into/out of for now, for what they do they're great. They are already PLENTY of other storage options as well. Betterstorage, aura cascade, magic bookshelves from Thuamcraft, AE2 just to name a couple... we dont need yet another storage mod.
