### ISSUE TITLE
Botania flowers -- too rare

### ISSUE THREAD

**Issue by MrScopi** [breakinblocks/everything-is-hostile#43]
I'm not sure if they are disabled on purpose, but I haven't found any flowers.

Additionally, the recipes for floral fertilizer are disabled.

If the quests are meant as the only source of flowers, then I think the player should be warned to use the petals sparingly.

Thanks!

**Comment by Milkyway3640** [comment]
The flowers are turned off,  they won't spawn in the world at all.  The quests are meant to be one if the sources,  but you can also plant the petals to get more flowers

**Comment by Saereth** [comment]
worst case scenario they also drop as loot in dungeons and from infernal mobs so all is not lost should players be careless with the quest rewards.
