### ISSUE TITLE
Botania: Black Lotus not working?

### ISSUE THREAD

**Issue by MrScopi** [breakinblocks/everything-is-hostile#44]
I had two Black Lotuses I found as treasure loot.  When I put them in my mana pool (which had some mana in it, per the Lexica), I still didn't have enough mana to even make one ingot of manasteel.

That doesn't seem right -- if they are turned down on purpose then I'd rather they get replaced with cobwebs in chests. :)

**Comment by Saereth** [comment]
Mana steel cost is increased greatly, 10,000 mana per ingot. If you use thaumium or angel steel instead of mundane iron it will be even cheaper than normal however. This encourages cross modding and self gates botania slightly for those merely seeking to rush it.
