### ISSUE TITLE
Green angel sword causes crashes when dying to the curse

### ISSUE THREAD

**Issue by MetalNinjaWolf** [breakinblocks/everything-is-hostile#45]
The green curse spreads to other players from the Green Angel Swords and when dying to the curse it causes some people to crash. Here is a crash log. http://pastebin.com/YZvXejMn

**Comment by Saereth** [comment]
This has been reported to the developer, will update when I know more

**Comment by Saereth** [comment]
Fixed next update

**Comment by Saereth** [comment]
Fixed next update
