### ISSUE TITLE
AbyssalCraft enchancements

### ISSUE THREAD

**Issue by Shinoow** [breakinblocks/everything-is-hostile#48]
Normally I'd have a small list of things here, but since I haven't tested the pack that much, I can't make a large list.
However, one thing that came to mind was the HQM quests involving killing specific AbyssalCraft mobs. Since there's hardly any native "mob icons", users could get confused regarding what they're supposed to kill (unless it's Depths Ghouls, since they have head blocks). For that, I created a small add-on which introduces head icons for all the other mobs found throughout the mod, which can be found at http://minecraft.curseforge.com/mc-mods/229609-abyssalcraft-heads
If I happen to come by anything else that can be enhanced, I'll be sure to point that out.
Also, on another note, I'd advice that the Necronomicon is mentioned around the HQM quests, so that the users know that they can find all sorts of information inside it, and that quests where you obtain items/blocks through things that aren't in vanilla Minecraft, use the "detection task" thingy for them to avoid dead ends.

**Comment by Saereth** [comment]
This is great, I'll be adding it to the pack today since I intend to get the abyssalcraft questlines in this weekend.

**Comment by Saereth** [comment]
Added Abyssalcraft Heads to the pack and added the HQM questlines in the next update
