### ISSUE TITLE
Hex values on items

### ISSUE THREAD

**Issue by Gammelkebab** [breakinblocks/everything-is-hostile#49]
Iron can occur with a hex value of :16 rendering it useless. Iron oreberry bushes are not usable in crafting without a hex value (:8) i think. Copper/Bronze seeds can only be crafted with forestry copper/bronze, which is unobtainable.

**Comment by Saereth** [comment]
The metadata requirement is intentional metadata :8 is the iron bush which is craftable with the rose bush; working on the forest recipes now...

**Comment by Saereth** [comment]
ok this should all be fixed with today's update
