### ISSUE TITLE
Unable to make boosted shards

### ISSUE THREAD

**Issue by Debu922** [breakinblocks/everything-is-hostile#54]
I am unable to make chromaticraft boosted shards. I have tossed in 24 berries in liquid chroma as suggested, and then tossed in the shards. The shards when tossed in show a particle effect of the respective shard colour. After some time(around 4-5 minutes to be exact), the chroma reverts back to its original colour(white) and then the shards disappear (visually), Upon entering the liquid chroma, I get the shard back but the old ones which were tossed in. 

It is a hindrance in the chromaticraft progression as they are required to create crystal repeaters, etc.

**Comment by Saereth** [comment]
Non issue
