### ISSUE TITLE
The Four Horsemen quest

### ISSUE THREAD

**Issue by SirSpence99** [breakinblocks/everything-is-hostile#55]
It is currently not completable because special mobs is overwriting Zombie, Creeper, and Enderman. Because of this you can only mutate the skeleton but not the other 3 mobs.

**Comment by Saereth** [comment]
Fixed via https://github.com/breakinblocks/everything-is-hostile/commit/bb5eeaa5edcac7c77152b104f3204f03b24c5ce9
