### ISSUE TITLE
Crash while using the Item Mover

### ISSUE THREAD

**Issue by calebh514** [breakinblocks/everything-is-hostile#62]
When I use the item mover on my ME system to try and get an item, I used sticks to test it out, I immediately get kicked from the server. Here's the puush of most of the log, it ends with me getting kicked from the server. 

http://puu.sh/joPvT/034ba371b7.txt

Looks like it might be some sort of issue with CC, Chisel, and AE?

**Comment by Saereth** [comment]
try this without your resourcepack and see if it does it

**Comment by ReikaKalseki** [comment]
This does not happen with just CC, Chisel, and AE (as my server, which has all three, has no issues). However, the log mentions Hardcore Questing, and it repeatedly OOBs in its packet handling. Packet handling errors result in a kick.

**Comment by Saereth** [comment]
Makes sense, I'll forward on to the HQm guys, thanks
