### ISSUE TITLE
Into the mouth of madness branch Quest "Romancing the stone" Not registering kills.

### ISSUE THREAD

**Issue by X2home** [breakinblocks/everything-is-hostile#63]
In the HQM questline called "into the mouth of madness" a quest called "Romancing the stone" is not registering any of the needed mobs, have tried all of them. (multiple times)

**Comment by Saereth** [comment]
This is the quest for the abyssalcraft mobs?

**Comment by Saereth** [comment]
Duplicate https://github.com/breakinblocks/everything-is-hostile/issues/56
