### ISSUE TITLE
Bug report: Into the Mouth of Madness quests

### ISSUE THREAD

**Issue by Shinoow** [breakinblocks/everything-is-hostile#64]
I went over the quests in this questline, and I found a couple of things that needs fixing (at least one of them has already been reported):
* Oblivion Becomes Me (should be all detection tasks, as none of the items are crafted)
* Romancing the Stone (kills aren't detecting) <--- already reported
* Dreaded Gateway Key (change to detection, as it is no longer crafted)
* Dreadium Ingots (change to detection instead, as the ingots are rarely crafted)
* The Omothol Necronomicon (the quest can be taken before all other quests, and it doesn't trigger when the item in question is crafted)
* Abyssal Wastelands Necronomicon (this quest should appear before Asorah, The Fallen, as this is the first Necronomicon upgrade)

**Comment by Saereth** [comment]
@Shinoow Thanks for the feedback, all of these are corrected in the next update!
