### ISSUE TITLE
Pressing "U" on almost any item in NEI or inventory crashes the game

### ISSUE THREAD

**Issue by Someweb** [breakinblocks/everything-is-hostile#66]
I cant press U any more ._. and now I don't know how to use stuff cause I dumb

**Comment by kvalek** [comment]
This is a problem with NEI-integration mod (and Java7 i think). Delete the mod and you should have no problems. You will lose most forestry recipes in NEI though.

**Comment by Someweb** [comment]
Is there any other way to get rid of this yet?

**Comment by Saereth** [comment]
This is a known issue, you can delete the nei integration mod for now, it's clientside only but forestry recipes wont show up. It's marked as fixed in the next version on the author's website so I imagine we'll see an update to fix it soon.
