### ISSUE TITLE
crashing problem

### ISSUE THREAD

**Issue by Shadowruler0** [breakinblocks/everything-is-hostile#74]
I am Playing version 2.3.1 and i keep crashing when i am testing the mod pack by generating chunks 
[crash-2015-12-17_23.15.52-server.txt](https://github.com/breakinblocks/everything-is-hostile/files/66294/crash-2015-12-17_23.15.52-server.txt)

**Comment by Saereth** [comment]
This looks to be a corrupt install missing one of the chocolate quest templates.  I will investigate this today. Meanwhile try reinstalling the pack

**Comment by Shadowruler0** [comment]
thank you for looking into it
i have been having this problem for a week and i have reinstalled it countless times

**Comment by Saereth** [comment]
Just to update you on this, we're working on a major pack update, due out tomorrow. In the meantime deleting the chocolate folder from the configs directory and relaunching should solve your issue.

**Comment by Shadowruler0** [comment]
that seemed to fix it thank you and good luck on the update :+1:
