### ISSUE TITLE
2.4c Crashing on startup

### ISSUE THREAD

**Issue by Asb44** [breakinblocks/everything-is-hostile#76]
Crash log: http://pastebin.com/kF86uF4r
2.3.1 runs just fine but when I try to run 2.4c the screen stays black, and then it closes out after a while.

**Comment by Saereth** [comment]
This appears to be a chromaticraft issue with the jar, we'll attempt to get a fresh copy on the repo asap

**Comment by Saereth** [comment]
Ok we uploaded a fresh copy, go into your cache and delete ALL the files, it's found here
http://i.imgur.com/5IxJLjS.png

then hit reinstall pack and it should work, let me know if you have any more issues with it

**Comment by Saereth** [comment]
Actually update to 2.4d, after clearing your cash, Dragonapi just updated as well
