### ISSUE TITLE
HQM Entry "What is this, Snow White?" Crash.

### ISSUE THREAD

**Issue by Soma-Logic** [breakinblocks/everything-is-hostile#80]
When clicking the quest to progress in the book along the Evilcraft Quest line, there is an immediate crash to desktop with no error screen, and this crashlog in the folder.

[crash-2015-12-26_19.56.35-client.txt](https://github.com/breakinblocks/everything-is-hostile/files/72581/crash-2015-12-26_19.56.35-client.txt)

**Comment by Saereth** [comment]
Fixed next update
