### ISSUE TITLE
Mod Suggestion: Garden Stuff

### ISSUE THREAD

**Issue by Lonemind** [breakinblocks/everything-is-hostile#83]
For the various gardening and natural builders out there, this mod is quite amazing. It adds flower beds that allow you to place multiple flowers into one block. It adds various other things that really spice up outdoor decorating. Take a look.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2163513-garden-stuff-v-1-7-0-updated-dec-06-15

**Comment by Saereth** [comment]
there's several more mods we'd like to have along with this but the pack is pretty large already. We'd need to remove something like decocraft to fit this in.
