### ISSUE TITLE
2 into 1?

### ISSUE THREAD

**Issue by KasBoot** [breakinblocks/everything-is-hostile#85]
Hello everyone,
I have a few things to say here:
1) if you craft a wooden bucket from project zulu and then click on an essence pool (ars magica 2) then you get a iron bucket of essence and if you empty you're bucket you have a normal bucket for 3 wood.
2) I posted a whitelist apply and said 2 times now I got added to the whitelist but It still says I'm not white-listed.

hope anyone can help :)

KasBoot

**Comment by Saereth** [comment]
what is your exact ingame name, kas_boot was added?

**Comment by KasBoot** [comment]
I see the problem.....
The exact name is Kas_Boot (with the K and B in caps).
thx for looking into it!
appreciated
