### ISSUE TITLE
Mod Suggestion: Hunger Overhaul

### ISSUE THREAD

**Issue by Lonemind** [breakinblocks/everything-is-hostile#87]
The pack seems incomplete without it. XD
Though I would request that you make sugar cane grow faster than HO's default since paper is highly needed in magic packs. Also, remove the biome requirements on seeds. Being limited to living in either a forest or plains makes for such a bland game.

**Comment by Someweb** [comment]
We have had this one in our pack before but it proved to me more of an annoyance to our players than something worth adding. Most people survive on whatever then find the best food and never switch again. The only way I would consider adding Hunger Overhaul again is compared with spice of life but to many people don't want it.

**Comment by Lonemind** [comment]
I have a love/hate relationship with Spice of Life. I love the concept and with enough tweaking can make quite a nice early/mid game challenge. Later on, though, it's just so tedious. I'll be building some grand dream when I get hungry and go for a burger. "Uh oh. No. I had that two days ago. I can't have it again. What can I eat that lasts long enough but I haven't eaten in the past month?" :P

**Comment by Someweb** [comment]
It is indeed a bit of a tricky mod. Although with our latest addition of cooking for blockheads that might be very solvable. The mod will show you all the things you can make with the ingredients you have.
Also you can tweaks how much variety you need to have in your "diet" so to speak.
I'll ask sae once more but I doubt we'll go to use it

**Comment by Saereth** [comment]
I personally like HO but too many people have spoken against it. I did however add applecore for some of the nice features it adds.
