### ISSUE TITLE
copper oreberry bush?

### ISSUE THREAD

**Issue by KasBoot** [breakinblocks/everything-is-hostile#88]
Hello everyone,
I recently found out that you cannot craft copper oreberry bushes while there is a recipe
4 clay and 1 iron oreberry bush
it is needed for a quest so it would be nice if it worked again :)

Cheers Kas

**Comment by Lonemind** [comment]
It appears there are two versions of the iron ore berry bush. One version works. One does not. Check the item ID. I don't know why this is so.

**Comment by KasBoot** [comment]
you only craft the copper oreberry bushes using the crafted iron ones.
sorry for the late response :P

**Comment by Saereth** [comment]
This should be fixed
