### ISSUE TITLE
Mystcraft?

### ISSUE THREAD

**Issue by KasBoot** [breakinblocks/everything-is-hostile#90]
I made 2 linking books one at spawn and one at my base
I put them into a book stand I can click on them but I cannot teleport?
is it disabled or just something else?

cheers
kasboot

**Comment by Saereth** [comment]
If you tp to the same dimension your link panels must be intra linking.  You craft those by dropping gold dust into the ink mixer and pulling out the page when the circle us green

**Comment by KasBoot** [comment]
ok thx you Saereth :)
