### ISSUE TITLE
Modpack Fails to Download through Technic Launcher

### ISSUE THREAD

**Issue by Murdermancer** [breakinblocks/everything-is-hostile#93]
When I hit the install button in the Technic Launcher, it produces the following error:

Error unzipping a file for the following pack: Everything is Hostile
Attempting to extract file everything-is-hostile-2.4c.zip, but it did not exist.
Please consult the modpack author.

Other modpacks seem to install without issue, so I suspect that this is not a local issue.

**Comment by Saereth** [comment]
This is resolved
