### ISSUE TITLE
Potion ID check

### ISSUE THREAD

**Issue by Lonemind** [breakinblocks/everything-is-hostile#94]
Might want to check the potion ID's.
It seems that the Potion effect from Hunger Overhaul, WellFed, is overlapped with Taint Withdrawl. Anytime you eat you get Taint Withdrawl and take damage for the duration of the effect.

**Comment by Saereth** [comment]
Makes sense, hunger overheaul was just added to the pack, will have a fix shortly

**Comment by Saereth** [comment]
https://github.com/breakinblocks/everything-is-hostile/blob/master/config/ThaumicExploration.cfg
