### ISSUE TITLE
Cannot download pack.

### ISSUE THREAD

**Issue by WhiteBear0211** [breakinblocks/everything-is-hostile#95]
On the technic launcher the pack starts downloading cofhcore, goes from 3% back to 0% then gives me an error.

**Comment by Saereth** [comment]
I am unable to reproduce this currently, whats the error?

**Comment by WhiteBear0211** [comment]
Error downloading the following pack:Everything is Hostile
Failed to download http://solder2.breakinblocks.com/repo/mods/cofhcore/cofhcore-[1.7.10]3.1.2-325.zip
Please consult modpack author.

That's the error I get when it gets up to donwloading cofhcore, all the mods before it seemed to have downloaded properly.

**Comment by Saereth** [comment]
I reuploaded that file to our solder repo and rehashed. I still cant reproduce the issue on my end but that may fix it for you

**Comment by WhiteBear0211** [comment]
That fixed it, downloaded and installed perfectly.
Thanks.
